- pydgraph/client.py
- pydgraph/client_stub.py
- pydgraph/errors.py
- pydgraph/meta.py
- pydgraph/txn.py
- pydgraph/util.py
- tests/helper.py
- tests/test_acct_upsert.py
- tests/test_bank.py
- tests/test_client.py
- tests/test_client_stub.py
- tests/test_essentials.py
- tests/test_queries.py
- tests/test_util.py
* Update maintainer fields to my name and email address.
* Fix most issues reported by pylint (some of them are false positives
so I am ignoring them.
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/37)
>  Fix formatting issues

- pydgraph/__init__.py
- pydgraph/client.py
- pydgraph/txn.py
- pydgraph/util.py
- tests/helper.py
- tests/test_util.py
linreadmap was removed from Dgraph and is no longer needed in clients.
Addresses #33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/39)
> Remove linreadmap.

- pydgraph/client.py
- pydgraph/txn.py
- tests/test_txn.py
Read-only transactions can be created by using `client.txn(read_only=True)` instead of `client.txn()`. Read-only transactions improve performance of queries by not going through the Raft proposal system when advancing the start ts. The start ts stays the same across the lifetime of the transaction. Mutations and commits are not allowed in read-only transactions.
The `client.query` helper method uses read-only transactions now. This addresses #27.
Closes #30.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/40)
> Add support for read-only transactions.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/47)
> Update CI to cover python 3.7

- CHANGELOG.md
- pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/52)
> Change version to 1.0.2

- examples/simple/simple.py
- examples/tls/mutualtls_example.py
- pydgraph/client.py
- tests/test_acct_upsert.py
- tests/test_essentials.py
- tests/test_queries.py
- tests/test_txn.py
Other clients do not have the query as part of the client interface,
only the transaction interface can do that. This change removes query
from the client interface so that it matches the rest of the clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/61)
> Remove query method from client.py

- CHANGELOG.md
- pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/62)
> Create version 1.0.4

- pydgraph/txn.py
In Python 3.7 the error variable here is not set and thus a wrong exception gets thrown. Switching this to the variable "mutate_error" fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/65)
> Fix error reference in transaction mutate function

- pydgraph/client_stub.py
Lastest versions of GRPC does not include the shutdown and destroy channel on _del_ call. (https://github.com/grpc/grpc/issues/12531).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/69)
> Free GRPC resources on stub close

- requirements.txt
As per #70, this PR changes the `protobuf` dependency from `==3.6.1` to `>=3.6.1`.
Closes #70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/71)
> Don't pin dependency versions in requirements.txt (#70)

- setup.py
Python >= 3.6 doesn't receive ImportError, but instead
ModuleNotFoundError.
I haven't performed exhaustive testing, apart from confirming that the following pattern works on Python 2.7:
```python
try:
import foobar
except ImportError:
print 'OK'
except ModuleNotFoundError:
print 'Never reached on Python 2.7'
```
I also didn't want to "dry" up the duplicated code since it's short and contains a function definition on the top level scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/81)
> Catch pypandoc ModuleNotFoundError

- setup.py
Throwing this error is causing issues for users that try to build
packages that depend on pydgraph.
See https://github.com/dgraph-io/pydgraph/issues/82 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/84)
> Do not throw errors in build steps if pypandoc is not found.

- examples/simple/simple.py
The simple.py [README.md](https://github.com/dgraph-io/pydgraph/blob/326a5b7d5a66f03162dce288a82f99f069c90d46/examples/simple/README.md) configures the Dgraph cluster with the default ports, so simple.py should connect to port 9080.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/93)
> Change simple example to connect to Dgraph's default port.

- setup.py
The format of the README file must be specified as markdown or pypi will
reject the package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/123)
> Use markdown as the description format.

- pydgraph/client.py
- tests/test_queries.py
The check_version call is in the client_stub but has not been exposed
in the client.
Fixes #128
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/131)
> Expose check_version client call.

- README.md
Add a section on how to authenticate pydgraph when the Dgraph instance
is behind a reverse TLS proxy.
Taken from the gRPC section in
https://graphql.dgraph.io/slash-graphql/advanced-queries/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/153)
> Add section on authentication of TLS reverse proxies.

- README.md
The error handling in the original was unnecessarily complicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/152)
> Improved example in readme

- pydgraph/client.py
Fixes issue from Discuss: https://discuss.dgraph.io/t/client-py-does-not-import-errors/9271
The `errors` module has been used without importing it first, I've added the required import statement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/151)
> Fix missing import of 'errors'

- README.md
Fixes the incorrect statement in the PR title, per DGRAPH-2777 and https://discuss.dgraph.io/t/f-strings-vs-variables/11606/3
* Some rewording in this section
* Clarification about what upsert blocks are and how to use them
* Updated a deprecated URL pointing to upsert block docs
On-hold pending resolution of TeamCity build errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/161)
> Docs (discuss feedback): fix incorrect statement about upsert blocks allowing one query and one mutation

- examples/simple/README.md
- examples/simple/requirements.txt
- examples/simple/simple.py
- examples/tls/.gitignore
- examples/tls/README.md
- examples/tls/docker-compose.yml
- examples/tls/requirements.txt
- examples/tls/tls_example.py
- pydgraph/client_stub.py
This updates examples to support Dgraph v21.03:
* updated requirements for pydgraph==21.3.0
* examples/simple/README.md - fixed embedded docker-compose for superflags
* examples/tls/docker-compose.yml - updated for superflags
* examples/tls/README.md - updated instructions for cert creation to work on all platforms (win/mac/lin)
* dgraph no longer released on mac/win, but as docker is common requirement, updated instructions work
* tested changes on mac os w/ docker-desktop using dgraph v21.03.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/171)
> fix - Refresh example for v21.03.x

- scripts/local-test.sh
- tests/docker-compose.yml
Test script was referencing requirements_dev.  We now require dev dependencies be installed before running script.  Also, we use the latest docker image now.
> chore(ci): fix test script + use latest docker image

- .github/workflows/ci-pydgraph-tests.yml
- tests/docker-compose.yml
CI was running against latest image.  This will not catch bugs until we push a dgraph release.  For CI we build dgraph image locally and run pydgraph CI against this image.  Also, we were not checking out the version of pydgraph on PR's.  We fix this issue.
> chore(ci): test against latest dgraph on main

- README.md
- pydgraph/client_stub.py
- tests/test_client.py
- tests/test_client_stub.py
This PR also deprecates from_slash_endpoint function. Fixes #189
> accept grpc endpoint or /graphql endpoint in from_cloud function

- examples/notebook/self_managed_cluster.ipynb
- pydgraph/client_stub.py
- tests/test_client_stub.py
This PR adds an Jupyter Notebook to the examples folder (capturing some learnings from the Knowledge Graph Conference).. Whilst testing a Dgraph Cloud version of the Notebook in this PR, I discovered a bug in the client_stub module whereby if both the protocol scheme (https) and the port number (:443) were included in the call to `from_cloud`, the connection would fail. This format was specifically illustrated in the README, so it was worth fixing. Although I did correct the example on the README to be the grpc endpoint value that is presented on the Dgraph Cloud Settings tab.
As mentioned, I attempted to add a Dgraph Cloud-specific Notebook, but data transfer quota issues are preventing me from testing that thoroughly (I opened a discussion in Slack), so this PR only includes a …
> Add Jupyter Notebook example

- pydgraph/client_stub.py
Although the `DgraphClientStub` constructor accepts custom gRPC options for connecting to on-prem/self-hosted Dgraph backends, the same cannot be passed to the `from_cloud` function while connecting to Cloud backends. 
This PR allows passing of gRPC options like `grpc.max_receive_message_length` to the `from_cloud` function.
> accept custom grpc options in from_cloud function

- .github/workflows/ci-aqua-security-trivy-tests.yml
- .github/workflows/ci-pydgraph-tests.yml
scheduled runs are failing due to notifications being sent to non-existent email.  Changing cron frequency will reset this.
> CI: resolve failing jobs

- pyproject.toml
This pull request updates the dependency specifications for `grpcio` and `protobuf` to allow for minor and patch version flexibility.
Addresses https://github.com/dgraph-io/pydgraph/issues/222
- Updated grpcio dependency from grpcio==1.54.0 to grpcio>=1.54.0,<2.0.0
- Updated protobuf dependency from protobuf==4.22.3 to protobuf>=4.22.3,<5.0.0
- **Flexibility**: This change allows the library to be compatible with a wider range of versions, making it easier to integrate into projects with different dependency requirements.
- **Compatibility**: Minor and patch versions are generally backward compatible. Allowing updates within these ranges enables the library to benefit from bug fixes and improvements.
- **Ease of Integration**: Reduces the likelihood of version conflicts, promoting …
> Allow flexible dependency versions

- CHANGELOG.md
- README.md
- examples/simple/simple.py
- pydgraph/client.py
- scripts/local-test.sh
- tests/test_connect.py
This PR adds support to open gRPC endpoints using "connection strings", specifically the `pydgraph.open()` function.
<h2><code>dgraph://{username:password@}host:port?args</code></h2>
<p><code>username</code> and <code>password</code> are optional. If username is provided, a password must also be present. If supplied, these credentials are used to log into the cluster thru the ACL mechanism.</p>
<p>Valid args:</p>
Arg | Value | Description
-- | -- | --
apikey | \<key\> | This is a Dgraph Cloud API key
bearertoken | \<access token\> | An access token
sslmode | disable | The default. Do not connect via TLS
  | require | This is not supported in pydgraph
  | verify-ca | Use TLS and verify the certificate found
The `sslmode=require` pair is not supported and will throw an Exception if used. …
> feat: add support for dgraph connection strings
