pydgraph/txn.py
Also fix bug introduced in previous commit (_read_only was not being set
during initialization).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/41)
=> Add preds support in pydgraph.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/42)
=> Add section on how to set auth tokens to README.

.gitignore, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/45)
=> Update grpcio to 1.18.0

requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/51)
=> Set version of grpcio using >= instead of ==

pydgraph/txn.py, tests/test_txn.py
Fixes #49 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/50)
=> Reject non-string keys or values in variable map.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/54)
=> Documentation for best-effort queries.

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/55)
=> Changelog for v1.0.3

README.md
Fixes #56 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/57)
=> Fix N-quad example.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/63)
=> Remove references to client.query() method from README.

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/66)
=> Create version 1.1.1

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/72)
=> Bump version to 1.1.2

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/73)
=> Update changelog for v1.1.2

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/83)
=> Bump version to 2.0.1

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/85)
=> Bump version to 2.0.2

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/90)
=> Update README with Conditional Upsert example

tests/test_type_system.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/92)
=> Simplify the type system in test cases

pydgraph/proto/api.proto, tests/test_upsert_block.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/104)
=> Sync proto files with dgo

examples/simple/simple.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/99)
=> Update Simple Example to use simplified type definitions in schema

README.md
Updating upsert documentation
- Removing condition from the upsert operation example
- Other minor code cleanup from upsert examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/106)
=> Updating upsert documentation

README.md
Please *carefully* check if the table is correct and feel free to do the needed changes or comment
Thanks,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/111)
=> Adds new 'Supported versions' section

README.md
Fixes #118 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/119)
=> Document timeout and credentials keyword arguments.

README.md, examples/simple/README.md, examples/simple/requirements.txt, examples/simple/simple.py, examples/tls/tls_example.py, pydgraph/util.py, tests/helper.py, tests/test_acct_upsert.py, tests/test_acl.py, tests/test_queries.py, tests/test_txn.py, tests/test_type_system.py, tests/test_upsert_block.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/120)
=> Fix test now that we do indexing in background

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/121)
=> Release new minor version with new protobuf changes.

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/125)
=> Change version and add changelog.

pydgraph/client.py
Fixes #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/130)
=> Clarify documentation of any_client.

scripts/local-test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/138)
=> Stop cluster if running tests fails.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/141)
=> Include mention of docker in README test instructions.

README.md, pydgraph/client.py, tests/test_async.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/144)
=> Handle exceptions when during an alter.

tests/test_txn.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/146)
=> Add test for mutation with facets.

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/145)
=> Update changelog and metadata for version 20.03.1

.github/ISSUE_TEMPLATE, .github/workflows/main.yml, ISSUE_TEMPLATE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/149)
=> Enabled  Issue Auto-close

examples/simple/README.md
Addresses DGRAPH-2347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/154)
=> docs: Add information about whitelist IPs

CHANGELOG.md, pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/158)
=> Release 20.07.0

README.md
Fixes GQLSAAS-544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/159)
=> docs(fix): add setup reference to grpcio v1.19.0 package

examples/simple/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/164)
=> chore: enabled syntax highlighting

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/166)
=> Docs(Cross-linking): Update with a link to Python client docs under /docs, minor edits to intro

CHANGELOG.md, pydgraph/client_stub.py, pydgraph/meta.py, pydgraph/proto/api.proto, pydgraph/proto/api_pb2.py, pydgraph/txn.py
- Prepare for release v21.03.0
- Add hash to response and txn context. These changes are needed by dgraph-io/dgraph#7659 which makes the transactions more robust.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/168)
=> chore: release v21.03.0

pydgraph/client_stub.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/169)
=> feat(Cloud gRPC client): Add from_cloud method.

pydgraph/client_stub.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/174)
=> fix: Missing variable in from_cloud.

pydgraph/meta.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/175)
=> Release 21.3.2.

examples/parse_datetime/README.md, examples/parse_datetime/parse_datetime.py
@chewxy 
Pull request related to discussion: [Pydgraph (feature request): Automatically parse datetime strings](https://discuss.dgraph.io/t/pydgraph-feature-request-automatically-parse-datetime-strings/14074/5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/pydgraph/170)
=> Adding example for datetime parsing

.github/workflows/cd-pydgraph.yml
Fixing some minor pipeline issues.  
Created a local fork and ran workflow here: https://github.com/joshua-goldstein/pydgraph/actions/runs/5073667102/jobs/9112960055
Successfully uploaded to TestPyPi (see here for how it will look): https://test.pypi.org/project/joshua-pydgraph-test-3/23.0.0/
=> chore(cd): pipeline fixes

pydgraph/client.py, pydgraph/client_stub.py, pydgraph/errors.py, pydgraph/txn.py, pydgraph/util.py, tests/helper.py, tests/test_acct_upsert.py, tests/test_async.py, tests/test_client.py, tests/test_client_stub.py, tests/test_essentials.py, tests/test_queries.py, tests/test_txn.py, tests/test_util.py
I'm just removing nonexistent emails and putting contact as email for the maintainer.
=> chore(docs): Remove invalid emails and non-maintainers.

examples/simple/simple.py, pydgraph/txn.py
I also modified the example(simple.py) to show how to print the commit_ts
=> return commit_ts in the function 'commit()' in txn.py

CHANGELOG.md
Prepare changelog for release.
=> chore: prepare changelog for v23.0.2 release

pydgraph/meta.py
Update the version in meta.py.
=> chore: update version in meta
